services:
  judge0-server:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:13
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0password
    volumes:
      - judge0_db:/var/lib/postgresql/data

  judge0-redis:
    image: redis:6
    restart: always

volumes:
  judge0_db:
