const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

/**
 * MonitoringEvent
 * ─────────────────────────────────────────────────────────────────────────────
 * Authoritative monitoring and proctoring events generated by Laptop (MediaPipe)
 * or Mobile (YOLO11s) camera pipelines, browser security hooks, or audio analyzers.
 */
const MonitoringEvent = sequelize.define('MonitoringEvent', {
  id: {
    type: DataTypes.BIGINT,
    autoIncrement: true,
    primaryKey: true,
  },
  monitoringSessionId: {
    type: DataTypes.STRING(128),
    allowNull: false,
    field: 'monitoring_session_id',
    comment: 'Associated MonitoringSession.sessionId',
  },
  attemptId: {
    type: DataTypes.BIGINT,
    allowNull: true,
    field: 'attempt_id',
    comment: 'Associated QuizAttempt.id, CodingAttempt.id, or Interview.id',
  },
  participantId: {
    type: DataTypes.BIGINT,
    allowNull: false,
    field: 'participant_id',
    comment: 'Participant User.id',
  },
  contextType: {
    type: DataTypes.ENUM('QUIZ', 'CODING', 'INTERVIEW'),
    allowNull: false,
    defaultValue: 'QUIZ',
    field: 'context_type',
  },
  source: {
    type: DataTypes.ENUM('LAPTOP', 'MOBILE'),
    allowNull: false,
    defaultValue: 'LAPTOP',
    field: 'source',
  },
  eventType: {
    type: DataTypes.STRING(64),
    allowNull: false,
    field: 'event_type',
    comment: 'Event name e.g. EYE_OFF_SCREEN_LEFT, HEAD_LOOKING_DOWN, PERSON_COUNT_ZERO, COMPOSITION_INVALID',
  },
  severity: {
    type: DataTypes.STRING(32),
    allowNull: false,
    defaultValue: 'INFO',
    field: 'severity',
  },
  scoreDelta: {
    type: DataTypes.FLOAT,
    allowNull: false,
    defaultValue: 0.0,
    field: 'score_delta',
    comment: 'Malpractice penalty score added by authoritative backend scoring engine',
  },
  durationMs: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    field: 'duration_ms',
    comment: 'Duration of detected condition in milliseconds',
  },
  occurredAt: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW,
    field: 'occurred_at',
  },
  confidence: {
    type: DataTypes.FLOAT,
    allowNull: false,
    defaultValue: 1.0,
    field: 'confidence',
  },
  evidenceRef: {
    type: DataTypes.STRING(512),
    allowNull: true,
    field: 'evidence_ref',
    comment: 'Path or URL to still frame evidence (for HIGH/CRITICAL severity events)',
  },
  metadata: {
    type: DataTypes.JSON,
    allowNull: true,
    field: 'metadata',
    comment: 'Detailed diagnostic data: yaw/pitch/roll, gaze vector, detected classes, bounding boxes',
  },
  idempotencyKey: {
    type: DataTypes.STRING(191),
    allowNull: true,
    unique: true,
    field: 'idempotency_key',
    comment: 'Unique hash of session + eventType + time-bucket to prevent duplicate scoring',
  },
}, {
  tableName: 'monitoring_events',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  indexes: [
    { fields: ['monitoring_session_id'] },
    { fields: ['attempt_id'] },
    { fields: ['participant_id'] },
    { fields: ['source'] },
    { fields: ['event_type'] },
    { fields: ['severity'] },
    { fields: ['occurred_at'] },
    { fields: ['idempotency_key'], unique: true },
  ],
});

module.exports = MonitoringEvent;
