// Dummy leaderboard data — 20 participants
export const DEPARTMENTS = ['Engineering', 'Design', 'Marketing', 'Sales', 'HR', 'Finance', 'Operations']

export const BADGES = {
  fire: { icon: '🔥', label: 'On Fire' },
  crown: { icon: '👑', label: 'Top Scorer' },
  lightning: { icon: '⚡', label: 'Speed Demon' },
  gem: { icon: '💎', label: 'Perfectionist' },
  rocket: { icon: '🚀', label: 'Fast Learner' },
  star: { icon: '⭐', label: 'Star Performer' },
}

export const RANK_TIERS = [
  { label: 'Diamond', color: '#a8edff', glow: '0 0 20px #a8edff88', min: 2000 },
  { label: 'Platinum', color: '#e2e8f0', glow: '0 0 20px #e2e8f088', min: 1500 },
  { label: 'Gold', color: '#fcd34d', glow: '0 0 20px #fcd34d88', min: 1000 },
  { label: 'Silver', color: '#94a3b8', glow: '0 0 20px #94a3b888', min: 500 },
  { label: 'Bronze', color: '#fb923c', glow: '0 0 20px #fb923c88', min: 0 },
]

export function getTier(xp) {
  return RANK_TIERS.find(t => xp >= t.min) || RANK_TIERS[RANK_TIERS.length - 1]
}

const leaderboardData = [
  {
    id: 1,
    name: 'Arjun Sharma',
    initials: 'AS',
    department: 'Engineering',
    score: 97.4,
    weeklyScore: 94.2,
    accuracy: 98.1,
    quizzesCompleted: 24,
    xp: 2480,
    badges: ['crown', 'gem', 'fire'],
    streak: 14,
  },
  {
    id: 2,
    name: 'Priya Nair',
    initials: 'PN',
    department: 'Design',
    score: 94.8,
    weeklyScore: 97.1,
    accuracy: 95.6,
    quizzesCompleted: 21,
    xp: 2200,
    badges: ['lightning', 'star'],
    streak: 9,
  },
  {
    id: 3,
    name: 'Ravi Kumar',
    initials: 'RK',
    department: 'Marketing',
    score: 91.3,
    weeklyScore: 88.5,
    accuracy: 93.0,
    quizzesCompleted: 19,
    xp: 1950,
    badges: ['rocket', 'fire'],
    streak: 7,
  },
  {
    id: 4,
    name: 'Sneha Patel',
    initials: 'SP',
    department: 'HR',
    score: 89.7,
    weeklyScore: 91.3,
    accuracy: 90.4,
    quizzesCompleted: 18,
    xp: 1820,
    badges: ['star'],
    streak: 5,
  },
  {
    id: 5,
    name: 'Vikram Rao',
    initials: 'VR',
    department: 'Finance',
    score: 87.2,
    weeklyScore: 85.0,
    accuracy: 88.9,
    quizzesCompleted: 17,
    xp: 1740,
    badges: ['lightning'],
    streak: 4,
  },
  {
    id: 6,
    name: 'Meera Joshi',
    initials: 'MJ',
    department: 'Engineering',
    score: 85.6,
    weeklyScore: 89.4,
    accuracy: 87.2,
    quizzesCompleted: 16,
    xp: 1600,
    badges: ['rocket'],
    streak: 6,
  },
  {
    id: 7,
    name: 'Aditya Singh',
    initials: 'AD',
    department: 'Sales',
    score: 83.9,
    weeklyScore: 82.1,
    accuracy: 85.5,
    quizzesCompleted: 15,
    xp: 1520,
    badges: ['fire'],
    streak: 3,
  },
  {
    id: 8,
    name: 'Lakshmi Iyer',
    initials: 'LI',
    department: 'Operations',
    score: 81.4,
    weeklyScore: 84.7,
    accuracy: 83.1,
    quizzesCompleted: 14,
    xp: 1430,
    badges: ['star'],
    streak: 5,
  },
  {
    id: 9,
    name: 'Karthik Menon',
    initials: 'KM',
    department: 'Engineering',
    score: 79.8,
    weeklyScore: 78.3,
    accuracy: 81.6,
    quizzesCompleted: 13,
    xp: 1340,
    badges: [],
    streak: 2,
  },
  {
    id: 10,
    name: 'Divya Reddy',
    initials: 'DR',
    department: 'Design',
    score: 78.2,
    weeklyScore: 80.9,
    accuracy: 79.4,
    quizzesCompleted: 13,
    xp: 1280,
    badges: ['lightning'],
    streak: 4,
  },
  {
    id: 11,
    name: 'Suresh Pillai',
    initials: 'SU',
    department: 'Finance',
    score: 76.5,
    weeklyScore: 74.2,
    accuracy: 78.0,
    quizzesCompleted: 12,
    xp: 1190,
    badges: [],
    streak: 1,
  },
  {
    id: 12,
    name: 'Ananya Das',
    initials: 'AN',
    department: 'Marketing',
    score: 74.9,
    weeklyScore: 77.6,
    accuracy: 76.3,
    quizzesCompleted: 12,
    xp: 1120,
    badges: [],
    streak: 3,
  },
  {
    id: 13,
    name: 'Rahul Bose',
    initials: 'RB',
    department: 'Sales',
    score: 73.1,
    weeklyScore: 71.8,
    accuracy: 74.7,
    quizzesCompleted: 11,
    xp: 1050,
    badges: [],
    streak: 2,
  },
  {
    id: 14,
    name: 'Pooja Tiwari',
    initials: 'PT',
    department: 'HR',
    score: 71.4,
    weeklyScore: 73.0,
    accuracy: 72.8,
    quizzesCompleted: 11,
    xp: 990,
    badges: [],
    streak: 1,
  },
  {
    id: 15,
    name: 'Nikhil Gupta',
    initials: 'NG',
    department: 'Engineering',
    score: 69.7,
    weeklyScore: 68.4,
    accuracy: 71.2,
    quizzesCompleted: 10,
    xp: 920,
    badges: [],
    streak: 0,
  },
  {
    id: 16,
    name: 'Shalini Verma',
    initials: 'SV',
    department: 'Operations',
    score: 68.0,
    weeklyScore: 70.5,
    accuracy: 69.5,
    quizzesCompleted: 10,
    xp: 860,
    badges: [],
    streak: 2,
  },
  {
    id: 17,
    name: 'Deepak Nair',
    initials: 'DN',
    department: 'Finance',
    score: 65.3,
    weeklyScore: 63.1,
    accuracy: 67.0,
    quizzesCompleted: 9,
    xp: 790,
    badges: [],
    streak: 1,
  },
  {
    id: 18,
    name: 'Asha Mishra',
    initials: 'AM',
    department: 'Design',
    score: 63.7,
    weeklyScore: 66.2,
    accuracy: 65.4,
    quizzesCompleted: 9,
    xp: 720,
    badges: [],
    streak: 0,
  },
  {
    id: 19,
    name: 'Rajesh Kaur',
    initials: 'RJ',
    department: 'Marketing',
    score: 61.2,
    weeklyScore: 59.8,
    accuracy: 63.0,
    quizzesCompleted: 8,
    xp: 640,
    badges: [],
    streak: 0,
  },
  {
    id: 20,
    name: 'Kavya Pillai',
    initials: 'KP',
    department: 'Sales',
    score: 58.5,
    weeklyScore: 61.4,
    accuracy: 60.1,
    quizzesCompleted: 8,
    xp: 580,
    badges: [],
    streak: 1,
  },
]

export default leaderboardData
