const LANGUAGE_CONFIG = {
  python: {
    name: 'Python',
    version: '3.11',
    extension: '.py',
    monaco: 'python',
    compile: null,
    run: { cmd: 'python3', args: (file) => [file] },
    dockerImage: 'python:3.11-slim',
    judge0Id: 71,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 1,
  },
  javascript: {
    name: 'JavaScript',
    version: 'Node 20',
    extension: '.js',
    monaco: 'javascript',
    compile: null,
    run: { cmd: 'node', args: (file) => [file] },
    dockerImage: 'node:20-slim',
    judge0Id: 63,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 1,
  },
  java: {
    name: 'Java',
    version: '17',
    extension: '.java',
    monaco: 'java',
    compile: { cmd: 'javac', args: (file) => [file], outFile: (f) => f.replace('.java', '.class') },
    run: { cmd: 'java', args: (file, dir) => ['-cp', dir, file.replace('.java', '')] },
    dockerImage: 'openjdk:17-slim',
    judge0Id: 62,
    timeLimitMultiplier: 3,
    memoryLimitMultiplier: 2,
  },
  cpp: {
    name: 'C++',
    version: 'C++17',
    extension: '.cpp',
    monaco: 'cpp',
    compile: { cmd: 'g++', args: (file, dir) => [file, '-o', `${dir}/a.out`, '-std=c++17', '-O2', '-lm'], outFile: () => 'a.out' },
    run: { cmd: (file, dir) => `${dir}/a.out`, args: () => [] },
    dockerImage: 'gcc:13-bookworm',
    judge0Id: 54,
    timeLimitMultiplier: 1,
    memoryLimitMultiplier: 1,
  },
  c: {
    name: 'C',
    version: 'C11',
    extension: '.c',
    monaco: 'c',
    compile: { cmd: 'gcc', args: (file, dir) => [file, '-o', `${dir}/a.out`, '-std=c11', '-O2', '-lm'], outFile: () => 'a.out' },
    run: { cmd: (file, dir) => `${dir}/a.out`, args: () => [] },
    dockerImage: 'gcc:13-bookworm',
    judge0Id: 50,
    timeLimitMultiplier: 1,
    memoryLimitMultiplier: 1,
  },
  csharp: {
    name: 'C#',
    version: '10',
    extension: '.cs',
    monaco: 'csharp',
    compile: { cmd: 'dotnet', args: (file, dir) => ['build', dir, '-o', `${dir}/out`], outFile: () => 'out' },
    run: { cmd: 'dotnet', args: (file, dir) => ['run', '--project', dir] },
    dockerImage: 'mcr.microsoft.com/dotnet/sdk:8.0',
    judge0Id: 51,
    timeLimitMultiplier: 3,
    memoryLimitMultiplier: 2,
  },
  typescript: {
    name: 'TypeScript',
    version: '5.x',
    extension: '.ts',
    monaco: 'typescript',
    compile: { cmd: 'npx', args: (file, dir) => ['tsc', file, '--outDir', dir, '--target', 'ES2020'] },
    run: { cmd: 'node', args: (file, dir) => [file.replace('.ts', '.js')] },
    dockerImage: 'node:20-slim',
    judge0Id: 74,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 1,
  },
  go: {
    name: 'Go',
    version: '1.22',
    extension: '.go',
    monaco: 'go',
    compile: { cmd: 'go', args: (file, dir) => ['build', '-o', `${dir}/a.out`, file], outFile: () => 'a.out' },
    run: { cmd: (file, dir) => `${dir}/a.out`, args: () => [] },
    dockerImage: 'golang:1.22-bookworm',
    judge0Id: 60,
    timeLimitMultiplier: 1,
    memoryLimitMultiplier: 1,
  },
  rust: {
    name: 'Rust',
    version: '1.77',
    extension: '.rs',
    monaco: 'rust',
    compile: { cmd: 'rustc', args: (file, dir) => [file, '-o', `${dir}/a.out`, '-O'], outFile: () => 'a.out' },
    run: { cmd: (file, dir) => `${dir}/a.out`, args: () => [] },
    dockerImage: 'rust:1.77-slim-bookworm',
    judge0Id: 73,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 1,
  },
  php: {
    name: 'PHP',
    version: '8.3',
    extension: '.php',
    monaco: 'php',
    compile: null,
    run: { cmd: 'php', args: (file) => [file] },
    dockerImage: 'php:8.3-cli',
    judge0Id: 68,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 1,
  },
  kotlin: {
    name: 'Kotlin',
    version: '1.9',
    extension: '.kt',
    monaco: 'kotlin',
    compile: { cmd: 'kotlinc', args: (file, dir) => [file, '-include-runtime', '-d', `${dir}/Main.jar`], outFile: () => 'Main.jar' },
    run: { cmd: 'java', args: (file, dir) => ['-jar', `${dir}/Main.jar`] },
    dockerImage: 'kotlin:latest',
    judge0Id: 78,
    timeLimitMultiplier: 3,
    memoryLimitMultiplier: 2,
  },
  swift: {
    name: 'Swift',
    version: '5.9',
    extension: '.swift',
    monaco: 'swift',
    compile: { cmd: 'swiftc', args: (file, dir) => [file, '-o', `${dir}/a.out`], outFile: () => 'a.out' },
    run: { cmd: (file, dir) => `${dir}/a.out`, args: () => [] },
    dockerImage: 'swift:5.9',
    judge0Id: 83,
    timeLimitMultiplier: 2,
    memoryLimitMultiplier: 2,
  },
};

const LANGUAGES = Object.entries(LANGUAGE_CONFIG).map(([id, cfg]) => ({
  id,
  name: cfg.name,
  version: cfg.version,
  monaco: cfg.monaco,
  extension: cfg.extension,
}));

function getLanguageConfig(lang) {
  const key = (lang || 'javascript').toLowerCase();
  return LANGUAGE_CONFIG[key] || LANGUAGE_CONFIG.javascript;
}

module.exports = { LANGUAGE_CONFIG, LANGUAGES, getLanguageConfig };
