const VERDICTS = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPILING: 'COMPILING',
  ACCEPTED: 'ACCEPTED',
  WRONG_ANSWER: 'WRONG_ANSWER',
  COMPILATION_ERROR: 'COMPILATION_ERROR',
  RUNTIME_ERROR: 'RUNTIME_ERROR',
  TIME_LIMIT_EXCEEDED: 'TIME_LIMIT_EXCEEDED',
  MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
  OUTPUT_LIMIT_EXCEEDED: 'OUTPUT_LIMIT_EXCEEDED',
  PRESENTATION_ERROR: 'PRESENTATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const VERDICT_PRIORITY = {
  [VERDICTS.COMPILATION_ERROR]: 1,
  [VERDICTS.MEMORY_LIMIT_EXCEEDED]: 2,
  [VERDICTS.TIME_LIMIT_EXCEEDED]: 3,
  [VERDICTS.RUNTIME_ERROR]: 4,
  [VERDICTS.OUTPUT_LIMIT_EXCEEDED]: 5,
  [VERDICTS.PRESENTATION_ERROR]: 6,
  [VERDICTS.WRONG_ANSWER]: 7,
  [VERDICTS.ACCEPTED]: 8,
  [VERDICTS.INTERNAL_ERROR]: 0,
};

const JUDGE0_STATUS_MAP = {
  3: VERDICTS.ACCEPTED,
  4: VERDICTS.WRONG_ANSWER,
  5: VERDICTS.TIME_LIMIT_EXCEEDED,
  6: VERDICTS.COMPILATION_ERROR,
  7: VERDICTS.RUNTIME_ERROR,
  8: VERDICTS.RUNTIME_ERROR,
  9: VERDICTS.RUNTIME_ERROR,
  10: VERDICTS.RUNTIME_ERROR,
  11: VERDICTS.RUNTIME_ERROR,
  12: VERDICTS.RUNTIME_ERROR,
  13: VERDICTS.MEMORY_LIMIT_EXCEEDED,
  14: VERDICTS.RUNTIME_ERROR,
  15: VERDICTS.PRESENTATION_ERROR,
};

function aggregateVerdict(results) {
  let worst = null;
  let worstPriority = Infinity;
  for (const r of results) {
    const p = VERDICT_PRIORITY[r.verdict] ?? 0;
    if (p < worstPriority) {
      worstPriority = p;
      worst = r.verdict;
    }
  }
  return worst || VERDICTS.INTERNAL_ERROR;
}

module.exports = { VERDICTS, VERDICT_PRIORITY, JUDGE0_STATUS_MAP, aggregateVerdict };
