# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - waveinint

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main_waveinint.yml'
  workflow_dispatch:

jobs:
  # =========================
  # BUILD JOB
  # =========================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  # =========================
  # DEPLOY JOB
  # =========================
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting OpenID Connect JWT token
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1F237F56D744B5B95EB9D4B517BB809 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_556981C8B5F247E988832183DE303034 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_863B4D16255C43EFB9EC76A74D5FD146 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'waveinint'
          slot-name: 'Production'
          package: .